/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import AppPackage.AnimationClass;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Operacion;

/**
 *
 * @author Juan
 */
public class viewCalculator extends javax.swing.JFrame {
    AnimationClass ac = new AnimationClass();
    Operacion o = new Operacion();
    int x,y;
    /**
     * Creates new form viewCalculator
     */
    public viewCalculator() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 27, 27));
        this.setLocationRelativeTo(null);
        txtNumero1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        btnRestar = new javax.swing.JButton();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        btnSumar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblNumero2 = new javax.swing.JLabel();
        lblNumero1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        pnlBarraTitulo = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRestar.setBackground(new java.awt.Color(0, 102, 0));
        btnRestar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(255, 255, 255));
        btnRestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menos-64px.png"))); // NOI18N
        btnRestar.setText("RESTAR");
        btnRestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        pnlContenido.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 170, 80));

        txtNumero2.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero2.setFont(new java.awt.Font("Consolas", 1, 80)); // NOI18N
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumero2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero2KeyTyped(evt);
            }
        });
        pnlContenido.add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 200, 110));

        txtNumero1.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero1.setFont(new java.awt.Font("Consolas", 1, 80)); // NOI18N
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumero1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero1KeyTyped(evt);
            }
        });
        pnlContenido.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 110));

        lblResultado.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(153, 255, 255));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgResultado3.jpg"))); // NOI18N
        lblResultado.setText("sin resultado");
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlContenido.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 800, 100));

        btnSumar.setBackground(new java.awt.Color(0, 102, 0));
        btnSumar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(255, 255, 255));
        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sumar-64px.png"))); // NOI18N
        btnSumar.setText("SUMAR");
        btnSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSumar.setName("btnSumar"); // NOI18N
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        pnlContenido.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 170, 80));

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 0));
        btnLimpiar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar-64px.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlContenido.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 170, 80));

        lblNumero2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumero2.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero2.setText("Numero 2");
        pnlContenido.add(lblNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        lblNumero1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNumero1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero1.setText("Numero 1");
        pnlContenido.add(lblNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        lblFondo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(153, 153, 153));
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        lblFondo.setText("by JuanChavez");
        lblFondo.setToolTipText("");
        lblFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlContenido.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 520));

        pnlBarraTitulo.setBackground(new java.awt.Color(204, 204, 204));
        pnlBarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBarraTituloMouseDragged(evt);
            }
        });
        pnlBarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBarraTituloMousePressed(evt);
            }
        });
        pnlBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizeOff-32px.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizeOn-32px.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        pnlBarraTitulo.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitOff-32px.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitOn-32px.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBarraTitulo.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CALCULADORA");
        pnlBarraTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(pnlBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        validar();
        try {
            o.setNumero1(Integer.parseInt(txtNumero1.getText()));
            o.setNumero2(Integer.parseInt(txtNumero2.getText()));
            mensaje("La Resta de "+o.getNumero1()+" - "+o.getNumero2()+" = "+o.restar());
            resultado();
        } catch (NumberFormatException e) {
            //e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        validar();
        try {
            o.setNumero1(Integer.parseInt(txtNumero1.getText()));
            o.setNumero2(Integer.parseInt(txtNumero2.getText()));
            mensaje("La Suma de "+o.getNumero1()+" + "+o.getNumero2()+" = "+o.sumar());
            resultado();
        } catch (NumberFormatException e) {
            //e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNumero1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyPressed
        borrarResultado();
    }//GEN-LAST:event_txtNumero1KeyPressed

    private void txtNumero2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyPressed
        borrarResultado();
    }//GEN-LAST:event_txtNumero2KeyPressed

    private void pnlBarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTituloMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlBarraTituloMousePressed

    private void pnlBarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBarraTituloMouseDragged
        this.setLocation(this.getX()+evt.getX()-x,this.getY()+evt.getY()-y);
    }//GEN-LAST:event_pnlBarraTituloMouseDragged

    private void txtNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyTyped
        validarNumeros(evt);
        maximoValor(evt, txtNumero1);
    }//GEN-LAST:event_txtNumero1KeyTyped

    private void txtNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyTyped
        validarNumeros(evt);
        maximoValor(evt, txtNumero2);
    }//GEN-LAST:event_txtNumero2KeyTyped
    
    void maximoValor(java.awt.event.KeyEvent evt, JTextField caja){
        char c = evt.getKeyChar();
        if (caja.getText().length()>=3) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            resultado();
            mensaje("Máximo 3 dígitos");
        }
    }
    
    void validarNumeros(java.awt.event.KeyEvent evt){
        String numero="0987654321";
        if (!numero.contains(evt.getKeyChar()+"")) {
            evt.consume();//evita escribir en pantalla que no sea numero
            resultado();
            mensaje("Ingrese Solo numeros");
        }
    }
    
    void resultado(){
        //mostrar mensaje
        ac.jLabelYUp(520, 420, 15, 5, lblResultado);
        ac.jLabelYUp(420, 520, 5, 15, lblResultado);
        ac.jLabelYUp(420, 520, 5, 15, lblResultado);
        ac.jLabelYUp(520, 420, 15, 5, lblResultado);
        ac.jLabelYUp(520, 420, 15, 5, lblResultado);
        ac.jLabelYUp(420, 520, 5, 15, lblResultado);
    }
    
    void mensaje(String texto){
        lblResultado.setText(texto);
    }
    
    void validar(){
        if (txtNumero1.getText().equals("")) {
            resultado();
            mensaje("ingrese primer dígito");
            txtNumero1.requestFocus();
            
        }else{
            resultado();
            mensaje("ingrese segundo dígito");
            txtNumero2.requestFocus();
        }
    }
    
    void borrarResultado(){
        ac.jLabelYDown(420, 520, 15, 5, lblResultado);
        //mensaje("");
    }
    
    void limpiar(){
        borrarResultado();
        txtNumero1.setText("");
        txtNumero2.setText("");
        txtNumero1.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel pnlBarraTitulo;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
